### ISSUE TITLE
Image with results from flybys (A Bent Field -> Using a Materialized View)

### ISSUE THREAD

**Issue by ruidfigueiredo** [red-4/curious-moon#16] opened 2018-01-21 17:04 UTC
The results on the images seem to have less rows than what's in the data

The enceladus_view create on page 122 (135 in the pdf) is created using an inner join with table event_types. 
If it is not created using a *left* join then the results on page 124 will be significantly less (19 rows vs 29 rows). It was pretty confusing for me when I tried it and it and the results I got didn't seem to match the results on the book.

But even with a left join the results don't match exactly. With inner join:

```sql
 2009-11-02 07:11:58 | Enceladus closest approach observations
 2009-11-02 07:11:58 | MAPS RS Campaign
 2009-11-02 07:39:58 | ICYMAP:  UV Surface Map
 2009-11-02 07:56:58 | Enceladus closest approach observations
 ```

With left join:

```sql
 2009-11-02 07:11:58 | Enceladus closest approach observations
 2009-11-02 07:11:58 | MAPS RS Campaign
 2009-11-02 07:36:58 | CIRS_120EN_ENCEL7001_INMS;
 2009-11-02 07:39:58 | ICYMAP:  UV Surface Map
 2009-11-02 07:56:58 | Enceladus closest approach observations
 ```

The exact query I used: 

```sql
select time_stamp::timestamptz at time zone 'GMT', 
title from enceladus_events 
where time_stamp::date = '2009-11-02' 
order by time_stamp;
```

**Comment by robconery** [comment] 2018-03-21 18:32
I don't know if I follow what the issue is nor quite how you got here. The `events` table and `event_types` table were built from the same data during normalization. There's even a `NULL` entry in there - so they should match up fine. I'll have a look, but if you could tell me more it would help.

**Comment by ruidfigueiredo** [comment] 2018-03-21 22:23
Hi @robconery 

Here's all of what I tried (I believe this is exactly the sql that is in the book):

SQL to create table events:

```
create table events(
         id serial primary key,
         time_stamp timestamp not null,
         title varchar(500),
         description text,
         event_type_id int references event_types(id),
         target_id int references targets(id),
         team_id int references teams(id),
         request_id int references requests(id),
         spass_type_id int references spass_types(id)
);

insert into events(
        time_stamp, title, description, event_type_id, target_id, team_id, request_id, spass_type_id
)
select 
        import.master_plan.start_time_utc::timestamp at time zone 'UTC',
        import.master_plan.title,
        import.master_plan.description,
        event_types.id as event_type_id,
        targets.id as target_id,
        teams.id as team_id,
        requests.id as request_id,
        spass_types.id as spass_type_id
from import.master_plan
inner join event_types on event_types.description = import.master_plan.library_definition
inner join teams on teams.description = import.master_plan.team
inner join targets on targets.description = import.master_plan.target
inner join requests on requests.description = import.master_plan.request_name
inner join spass_types on spass_types.description = import.master_plan.spass_type;
```
Then the enceladus_events view:

```
create materialized view enceladus_events as
select 
        events.id,
        title,
        events.description,
        time_stamp,
        time_stamp::date as date,
        event_types.description as event,
        to_tsvector(concat(events.description, ' ', events.title)) as search
from events
inner join event_types on event_types.id = event_type_id
where target_id = 28
order by time_stamp;
```
(for me 28 is the id for enceladus in the targets table)

And this query:

select time_stamp::timestamptz,
title from enceladus_events 
where time_stamp::date = '2009-11-02' 
order by time_stamp;

These are the results I'm getting:

```
     time_stamp      |                       title                       
---------------------+---------------------------------------------------
 2009-11-02 01:13:58 | Scatterometry/Radiometry of Enceladus
 2009-11-02 06:41:58 | MAPS 120EN Campaign
 2009-11-02 07:11:58 | MAPS RS Campaign
 **2009-11-02 07:11:58 | Enceladus closest approach observations**
 2009-11-02 07:39:58 | ICYMAP:  UV Surface Map
 **2009-11-02 07:56:58 | Enceladus closest approach observations**
 2009-11-02 08:03:58 | ICYMAP:  UV Surface Map
 2009-11-02 08:13:58 | ICYMAP:  UV of plume occulting Saturn
 2009-11-02 08:13:58 | Enceladus
 2009-11-02 08:34:00 | Enceladus targeted flyby
 2009-11-02 09:41:58 | Enceladus
 2009-11-02 09:41:58 | ICYMAP:  UV of Plume Occulting Saturn
 2009-11-02 09:41:58 | CIRS_120EN_FP1STARE001_ENGR
 2009-11-02 10:03:58 | CIRS_120EN_ENFP1MAP001_PRIME;
 2009-11-02 10:03:58 | ICYLON:  Icy Satellite Longitude / Phase Coverage
 2009-11-02 10:03:58 | Enceladus
 2009-11-02 11:44:00 | ICYLON:  Icy Satellite Longitude / Phase Coverage
 2009-11-02 11:44:00 | Enceladus
 2009-11-02 17:00:00 | GSE pass for Enceladus' mass
(19 rows)
```
The results look different from the book, I can't understand why. For example there's only one row between the closest approach observations where in the book there's 2.

**Comment by robconery** [comment] 2018-03-22 19:10
I just reran tested the code and it looks somewhat similar though it might be ordered differently. I'm going to close this for now as some changes that I've made from other issues might have addressed this.

**Closed by robconery** 2018-03-22 19:10 UTC
Labels: oddness, question
