### ISSUE TITLE
Text explaining makefile references target lookup that isn't in the Makefile (Transit -> Using Make)

### ISSUE THREAD

**Issue by ruidfigueiredo** [red-4/curious-moon#14] opened 2018-01-21 16:36 UTC
On page 40 (page 55 in the pfd) explains how to specify that a makefile target depends on another target, specifically:

`lookup: import`

It goes on to say: 

>Specifies that the lookups target can’t be built unless the import target has been built. The import target can’t be built unless the master target has been built. Simple.

If this was just a "loose" example of what how to make a target depend on another it would be fine, but the description goes on to mention that the _import_ target depends on the _master_ target which are on the makefile.

**Comment by adam-beck** [comment] 2018-01-29 06:13
Duplicate of #5

**Comment by robconery** [comment] 2018-03-21 18:33
Thanks - this has been reported. Will fix in next rev.

**Closed by robconery** 2018-03-21 18:33 UTC
